apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-svc-monitor
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: [user, project, payment, promo]
  endpoints:
    - targetPort: 80
      path: /metrics
      interval: 15s
