apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: crowdfunding-app-payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: PAYMENT_DB_URL
            - name: POSTGRES_MIGRATIONS_DIR
              value: /app/migrations/postgres
            - name: PROJECT_SVC_URL
              value: http://project-svc.back.svc.cluster.local
            - name: KAFKA_BROKERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: PROJECT_TOPIC
              value: project
            - name: PROJECT_GROUP_ID
              value: payment
            - name: CONTRIBUTION_TOPIC
              value: contribution
