apiVersion: apps/v1
kind: Deployment
metadata:
  name: promo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promo
  template:
    metadata:
      labels:
        app: promo
    spec:
      containers:
        - name: promo
          image: crowdfunding-app-promo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: PROMO_DB_URL
            - name: POSTGRES_MIGRATIONS_DIR
              value: /app/migrations/postgres
            - name: KAFKA_BROKERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: USER_TOPIC
              value: user
            - name: USER_GROUP_ID
              value: promo
