apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: crowdfunding-app-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: PROJECT_DB_DSN
            - name: KAFKA_BROKERS
              value: my-cluster-kafka-bootstrap:9092
            - name: PROJECT_TOPIC
              value: project
