metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

    service:
      enabled: true

    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prom-stack

ingressRoute:
  dashboard:
    enabled: true
