services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    ports:
      - 80:80
      - 11004:8080  # dashboard
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro

  noop:
    image: traefik/whoami
    container_name: noop

  pg:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: default
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:5.4.1-standalone
    container_name: adminer
    ports:
      - 11000:8080

  user:
    build:
      context: ../../../user
    container_name: user
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      POSTGRES_URL: postgres://app:app@postgres:5432/users?sslmode=disable
      POSTGRES_MIGRATIONS_DIR: /app/migrations/postgres
      REDIS_URL: redis://redis:6379
      JWT_SECRET: not-a-secret
      AVATARS_BASE_URL: http://localhost:9000/avatars
      KAFKA_BROKERS: kafka:9092
      USER_TOPIC: user
    ports:
      - 10000:80

  redis:  
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  inredis:
    image: redislabs/redisinsight:3.0
    ports:
      - 11001:5540

  kafka:
    image: confluentinc/cp-kafka:latest 
    container_name: kafka
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      CLUSTER_ID: abcdefghijklmnopqrstuv

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # KAFKA_NUM_PARTITIONS: 1
    ports:
      - 29092:29092
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server 127.0.0.1:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

  kafka-init:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: >
      sh -c "
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic user --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic project --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic contribution --partitions 1 --replication-factor 1
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 11002:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

  project:
    build:
      context: ../../../project
    container_name: project
    depends_on:
      pg:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      promo:
        condition: service_started
    environment:
      POSTGRES_DSN: postgres://app:app@postgres:5432/projects?sslmode=disable
      POSTGRES_MIGRATIONS_DIR: /app/migrations/postgres
      KAFKA_BROKERS: kafka:9092
      PROJECT_TOPIC: project
      CONTRIBUTION_TOPIC: contribution
      CONTRIBUTION_CONSUMER_GROUP: project
      PROMO_BASE_URL: http://promo
    ports:
      - 10001:80
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost/metrics >/dev/null 2>&1"]  # TODO: healthcheck
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 11003:9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./minio/default-avatars:/default-avatars
      - ./minio/user-avatars:/user-avatars
    entrypoint: >
      sh -c "
        mc alias set local http://minio:9000 minioadmin minioadmin &&
        mc mb --ignore-existing local/avatars &&
        mc anonymous set download local/avatars &&
        mc cp /default-avatars/* local/avatars/defaults/ &&
        mc cp --recursive /user-avatars/ local/avatars/users/
      "

  promo:
    build:
      context: ../../../promo
    container_name: promo
    depends_on:
      pg:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    environment:
      POSTGRES_URL: postgres://app:app@postgres:5432/promocodes?sslmode=disable
      POSTGRES_MIGRATIONS_DIR: /app/migrations/postgres
      KAFKA_BROKERS: kafka:9092
      USER_TOPIC: user
      USER_GROUP_ID: promo
    ports:
      - 10002:80

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 11005:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 11006:3000

  payment:
    build:
      context: ../../../payment
    container_name: payment
    depends_on:
      pg:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      project:
        condition: service_started  # TODO: change to healthy
    environment:
      POSTGRES_URL: postgres://app:app@postgres:5432/payments?sslmode=disable
      POSTGRES_MIGRATIONS_DIR: /app/migrations/postgres
      PROJECT_SVC_URL: http://project
      KAFKA_BROKERS: kafka:9092
      PROJECT_TOPIC: project
      PROJECT_GROUP_ID: payment
      CONTRIBUTION_TOPIC: contribution
    ports:
      - 10003:80

volumes:
  grafana-data:
