apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: crowdfunding-app-user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: USER_DB_URL
            - name: POSTGRES_MIGRATIONS_DIR
              value: /app/migrations/postgres
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: JWT_SECRET
            - name: AVATARS_BASE_URL
              value: https://img.app.local/avatars
            - name: KAFKA_BROKERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: USER_TOPIC
              value: user
